// <auto-generated />
using System;
using InfrastructureData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfrastructureData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412222833_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfrastructureCore.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CambiosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("CambiosNuevos")
                        .HasColumnType("text");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("text");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TipoAccion");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.Incidente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AsignadoAId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InfrastructuraId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotasResolucion")
                        .HasColumnType("text");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("InfrastructuraId");

                    b.HasIndex("Estado", "Severidad");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.Infraestructura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CapacidadActual")
                        .HasColumnType("integer");

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("Region", "Estado");

                    b.ToTable("Infraestructuras");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("InfrastructureCore.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.Incidente", b =>
                {
                    b.HasOne("InfrastructureCore.Entities.Usuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InfrastructureCore.Entities.Infraestructura", "Infraestructura")
                        .WithMany("Incidentes")
                        .HasForeignKey("InfrastructuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("Infraestructura");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.Infraestructura", b =>
                {
                    b.HasOne("InfrastructureCore.Entities.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("InfrastructureCore.Entities.Infraestructura", b =>
                {
                    b.Navigation("Incidentes");
                });
#pragma warning restore 612, 618
        }
    }
}
